#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Konstanten
SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1380, 690
JUMP_VELOCITY = 8
X_STARTING_POSITION = 10
Y_STARTING_POSITION = 595
PLAYER_STATIC_X = (SCREEN_WIDTH // 2)
PLAYER_HITBOX_PADDING_X = 30
PLAYER_HITBOX_PADDING_Y = 15
