#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Constants and Parameters for Q Learning

# Control Player
MOVE_RIGHT = 0
MOVE_LEFT = 1
JUMP = 2

NUMBER_EPISODES = 25000
MAX_STEPS_PER_EPISODE = 1500
MOVE_RIGHT_REWARD = - 5
MOVE_LEFT_REWARD = 5
JUMP_REWARD = 50
DIE_REWARD = 50000
COIN_REWARD = 5000
OVERCOME_ENEMY_REWARD = 2000
OVERCOME_PLATFORM_REWARD = 1500

# ALPHA:
LEARNING_RATE = 0.1
# GAMMA:
DISCOUNT_RATE = 0.99

# EPSILON:
EXPLORATION_RATE = 1
MAX_EXPLORATION_RATE = 1
MIN_EXPLORATION_RATE = 0.01
EXPLORATION_DECAY_RATE = 0.01
